services:
  - type: web
    name: wzmlx-telegram-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API
        sync: false
      - key: TELEGRAM_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        sync: false
      - key: UPSTREAM_REPO
        sync: false
      - key: UPSTREAM_BRANCH
        value: wzv3
    autoDeploy: true
    region: oregon
